server:
  port: 8047
spring:
  application:
    name: spring-cloud-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}    # 注册到consul的服务名称
    config:
      server:
        native:
          search-locations: classPath:/config/dev, classPath:/config/test
  profiles:
    active: native #本地配置文件必须开启本地环境

