spring:
  datasource:
    # 数据库访问配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bl-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      maxActive: 20
      min-idle: 5
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 stat,wall,log4j
      filters: stat
      # 配置一个连接在池中最大生存的时间，单位是毫秒 7小时
      maxEvictableIdleTimeMillis: 25200000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true

#mybatis-plus:
#  configuration:
#    #指定 MyBatis 所用日志的具体实现，未指定时将自动查找。
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #是否开启驼峰命名自动映射，即从经典数据库列名 A_COLUMN 映射到经典 Java 属性名 aColumn。
#    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      db-type: mysql
#      field-strategy: not_null
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      table-prefix: t_
#      table-underline: true
#  mapper-locations: classpath:/mapper/*.xml

mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      db-type: mysql
      field-strategy: not_null
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: t_
      table-underline: true
  mapper-locations: classpath:/mapper/*.xml